version: '3.3'
services:
  frontend:
    image: nureman/234-deploy-frontend:latest
    ports:
      - "8087:3000"
    environment:
      - mongodb=mongodb://54.197.77.253:8089/frontend
  mongodb:
    image: mongo:latest
    ports:
      - "8089:27017"